agency/agency/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("mainApp.urls")),
    path('news/', include("mainApp.urls")),
    path('about/', include("mainApp.urls")),
    path('service/', include("service.urls")),
    path('service/catalog-ap/', include("flats.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

agency/flats/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.catalog_ap, name='catalog_ap'),
    path('catalog-ap/<slug:slug>/', views.FlatDetailView.as_view(), name='flat-detail'),
]

agency/service/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.service, name='service'),
    path('catalog-nb/', views.catalog_nb, name='catalog_nb'),
    path('catalog-nb/<slug:slug>/', views.ComplexDetailView.as_view(), name='complex-detail'),
    path('sell/', views.Sell.as_view(), name='sell'),

]

agency/service/models.py
from django.db import models
from .utils import *
import datetime


class Complex(models.Model):
    name = models.CharField(max_length=50, verbose_name='Название')
    slug = models.SlugField(blank=True, verbose_name='Слаг')
    description = models.TextField(verbose_name='Описание')
    lat = models.FloatField(blank=True, null=True, verbose_name='Широта')
    lon = models.FloatField(blank=True, null=True, verbose_name='Долгота')
    img = models.ImageField(upload_to='complex/', verbose_name='Превью')

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = from_cyrillic_to_eng(str(self.name))
        super().save(*args, **kwargs)

    def __str__(self):
        return '%s' % self.name

    class Meta:
        verbose_name = 'Жилой комплекс'
        verbose_name_plural = 'Жилые комплексы'


class ComplexGallery(models.Model):
    complex = models.ForeignKey(Complex, on_delete=models.CASCADE, blank=True, verbose_name='Название ЖК')
    gal_img = models.ImageField(upload_to='complex/gallery/', blank=True, verbose_name='Фотография')

    def __str__(self):
        return '%s' % self.complex.name

    class Meta:
        verbose_name = 'Фотография ЖК'
        verbose_name_plural = 'Фотографии ЖК'


class House(models.Model):
    complex = models.ForeignKey(Complex, on_delete=models.CASCADE, blank=True, verbose_name='Комплекс')
    house_number = models.IntegerField(verbose_name='Номер дома')
    num_complex = models.IntegerField(verbose_name='Номер дома по счёту в этом комплексе', blank=True, null=True)

    def __str__(self):
        return '%s дом №%s' % (self.complex.name, self.house_number)

    class Meta:
        verbose_name = 'Дом'
        verbose_name_plural = 'Дома'


class Apartment(models.Model):
    house = models.ForeignKey(House, on_delete=models.CASCADE, blank=True, verbose_name='Дом')
    apartment_number = models.IntegerField(verbose_name='Номер')
    level = models.IntegerField(verbose_name='Этаж')
    room = models.IntegerField(verbose_name='Кол-во комнат')
    square = models.FloatField(verbose_name='Площадь')
    finishing = models.BooleanField(default=False, verbose_name='Отделка')
    price_m = models.DecimalField(max_digits=7, decimal_places=1, verbose_name='Цена за м2')
    price_total = models.DecimalField(max_digits=10, decimal_places=1, verbose_name='Цена за объект')
    plan_img = models.ImageField(upload_to='complex/apartment/', verbose_name='Планировка')
    num_house = models.IntegerField(verbose_name='Номер квартиры по счёту в этом комплексе', blank=True, null=True)

    def __str__(self):
        return '%s' % self.apartment_number

    class Meta:
        verbose_name = 'Квартира'
        verbose_name_plural = 'Квартиры'


class SaleOrder(models.Model):
    name = models.CharField(max_length=30, verbose_name='Имя')
    phone = models.CharField(max_length=11, verbose_name='Номер телефона')
    email = models.EmailField(verbose_name='Почта')
    message = models.TextField(verbose_name='Сообщение пользователя')
    date = models.DateTimeField(blank=True, null=True, verbose_name='Дата')

    def save(self, *args, **kwargs):
        if not self.date:
            self.date = datetime.datetime.now()
        super().save(*args, **kwargs)

    class Meta:
        verbose_name = 'Заявка на продажу квартиры'
        verbose_name_plural = 'Заявки на продажу квартир'

agency/service/forms.py
from django import forms
from .models import *


class SaleOrderForm(forms.ModelForm):

    class Meta:
        model = SaleOrder
        fields = ['name', 'phone', 'email', 'message']
        exclude = [""]
        widgets = {
            "comment": forms.Textarea(attrs={
                'placeholder': 'Оставьте сообщение...',
                'required': '',
                'rows': '8'})
        }

agency/service/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import DetailView, FormView

from .forms import *


def service(request):
    """Раздел 'Услуги' """
    active = ['service']
    return render(request, 'service/service.html', locals())


def catalog_nb(request):
    """Каталог новостроек"""
    active = ['service']
    complex_list = Complex.objects.all()
    paginator = Paginator(complex_list, 3)

    page = request.GET.get('page')
    try:
        complexes = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        complexes = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        complexes = paginator.page(paginator.num_pages)
    page_range = paginator.page_range
    return render(request, 'service/catalog-nb.html', {"complexes": complexes,
                                                       "page_range": page_range,
                                                       "active": active})


class ComplexDetailView(DetailView):
    """Отображение комплекса"""
    active = ['service']
    model = Complex
    template_name = 'service/complex.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['gallery'] = ComplexGallery.objects.filter(complex=context['complex'])
        context['houses'] = House.objects.filter(complex=context['complex'])
        context['apartments'] = {h.pk: Apartment.objects.filter(house=h) for h in context['houses']}
        for h in context['houses']:
            print(h.id)

        return context


class Sell(FormView):
    """Продажа квартиры"""
    active = ['service']
    model = SaleOrder
    form_class = SaleOrderForm
    template_name = 'service/sell-ap.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['sale_order_form'] = SaleOrder()
        return context

    def post(self, request, *args, **kwargs):
        form = SaleOrderForm(request.POST or None)
        if request.method == 'POST' and form.is_valid():
            new_form = form.save(commit=False)
            new_form.save()
        return HttpResponseRedirect(self.request.path_info)

agency/service/templates/service/catalog-nb.html
{% extends 'base.html' %}

{% block content %}
{% load static %}

<div class="container block">
      <div class="container">
          <div class="row">
              <div class="col-lg-10 offset-1">
                  <h1>Каталог новостроек</h1>
                  <hr width="271px">

                  <nav class="page-nav articles-nav">
                    <ul class="pagination">
                        {% if complexes.has_previous %}
                            <a class="prev-el" href="?page={{ complexes.previous_page_number }}">
                                <i class="fa fa-arrow-left" aria-hidden="true"></i>
                            </a>
                        {% endif %}

                        {% for n in complexes.paginator.page_range %}
                            {% if n > complexes.number|add:-4 and n < complexes.number|add:4 %}
                                 <li class="pagination-item">
                                     <a href='?page={{ n }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}'>
                                         <p class="page-num {% if n == complexes.number %}page-action{% endif %}">{{ n }}</p>
                                     </a>
                                 </li>
                            {% endif %}
                        {% endfor %}

                        {% if complexes.has_next %}
                            <a class="prev-el" href="?page={{ complexes.next_page_number }}">
                                <i class="fa fa-arrow-right" aria-hidden="true"></i>
                            </a>
                        {% endif %}
                    </ul>
                </nav>


                <div class="building-cards">
                    {% for complex in complexes %}
                    <div class="building-card" style="background-image: url({{ complex.img.url }}); ">
                        <div class="card-info">
                            <p class="option-info-text card-title">{{ complex.name }}</p>
                                <a href="{% url 'complex-detail' slug=complex.slug %}">
                                    <button class="btn btn-primary read-more" >
                                        Подробнее
                                    </button>
                                </a>
                        </div>

                    </div>
                    {% endfor %}
                </div>

                <nav class="page-nav articles-nav ">
                    <ul class="pagination">
                        {% if complexes.has_previous %}
                            <a class="prev-el" href="?page={{ complexes.previous_page_number }}">
                                <i class="fa fa-arrow-left" aria-hidden="true"></i>
                            </a>
                        {% endif %}

                        {% for n in complexes.paginator.page_range %}
                            {% if n > complexes.number|add:-4 and n < complexes.number|add:4 %}
                                 <li class="pagination-item">
                                     <a href='?page={{ n }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}'>
                                         <p class="page-num {% if n == complexes.number %}page-action{% endif %}">{{ n }}</p>
                                     </a>
                                 </li>
                            {% endif %}
                        {% endfor %}

                        {% if complexes.has_next %}
                            <a class="prev-el" href="?page={{ complexes.next_page_number }}">
                                <i class="fa fa-arrow-right" aria-hidden="true"></i>
                            </a>
                        {% endif %}
                    </ul>
                </nav>



              </div>
          </div>
      </div>
  </div>

{% endblock %}

agency/service/templates/service/complex.html
{% extends 'base.html' %}
{% load static %}
{% block header %}
<link rel="stylesheet" href="{% static 'mainApp/css/table-card.css' %}">
{% endblock %}

{% block content %}


  <div class="continer block">
    <div class="row"  id="all">
      <div class="col-lg-10 offset-1">
        <h1>{{ complex.name }}</h1>
        <hr width="50%" >

        <div class="descr-section">
          <h2 class="complex-section">Описание жилого комлекса</h2>
          <p class="complex-descr">{{ complex.description }}</p>

        </div>

        <div class="descr-section">
          <h2>Расположение</h2>
          <div id="map" class="map"></div>
        </div>


        <div class="gallery-section">
          <h2 class="text-left">Фотографии</h2>

            <div class="gallery-i">
              {% if gallery %}
                {% for img in gallery %}
                  <div class="col-lg-3 col-sm-5 thumb">
                    <a data-fancybox="gallery" href="{{ img.gal_img.url }}">
                      <img class="img-fluid" src="{{ img.gal_img.url }}" alt="...">
                    </a>
                  </div>
                {% endfor %}
              {% endif %}
            </div>
      </div>

      <div class="house-section">
        <h2 class="text-left">Дома</h2>
        <div class="h-cards-wrapper">
          {% for house in houses %}

          <div class="h-card">
            <div class="h-card-info">
              <p class="house-title">Дом {{ house.house_number }}</p>
                 <button class="btn btn-primary read-more h-btn" id="showCard" onClick="viewHouseCard({{house.num_complex}})" >
                  Подробнее
                </button>
            </div>
          </div>

          <div class="house-card" id="house-card">
            <button class="closeCard" onClick="closeHouseCard({{house.num_complex}})">
              <i class="fa fa-times" aria-hidden="true"></i>
            </button>

            <div class="card-content">
              <h1 class="white h-card-title">Дом {{ house.house_number }}</h1>
              <table class="table-container">

                <tr>
                  <th>Номер <br> квартиры</th>
                  <th>Этаж</th>
                  <th>Кол-во <br> комнат</th>
                  <th>Площадь</th>
                  <th>Отделка</th>
                  <th>Цена <br> за м2</th>
                  <th>Цена за <br> объект</th>
                  <th>Планировка</th>
                </tr>

                <tr>
                  {% for ap in house.apartment_set.all   %}
                    <tr>
                        <td>{{ap.apartment_number}}</td>
                        <td>{{ap.level}}</td>
                        <td>{{ap.room}}</td>
                        <td>{{ap.square}}</td>
                        <td>
                          {% if ap.finishing %}
                            С отделкой
                          {% else %}
                            Без отделки
                          {% endif %}
                        </td>
                        <td>{{ap.price_m}}</td>
                        <td>{{ap.price_total}}</td>
                        <td><button class="view-plan" onClick="viewHousePlan({{ ap.num_house }})"><i class="fa fa-eye" aria-hidden="true"></i></button></td>
                    </tr>


                <div class="house-plan" id="house-plan">
                  <button class="closeCard closePlan" onClick="closeHousePlan({{ ap.num_house }})">
                    <i class="fa fa-times" aria-hidden="true"></i>
                  </button>

                  <h1 class="h-card-title">Квартира {{ap.apartment_number}}</h1>
                  <div class="app-info-wrapper">
                    <p class="app-info">Дом: {{house.house_number}}</p>
                    <p class="app-info">Этаж: {{ap.level}}</p>
                    <p class="app-info">Кол-во комнат: {{ap.room}}</p>
                    <p class="app-info">Площадь: {{ap.square}}</p>
                    <p class="app-info">Цена за м2: {{ap.price_m}}</p>
                    <p class="app-info">Цена за квартиру: {{ap.price_total}}</p>
                    <p class="app-info">
                      {% if ap.finishing %}
                        С отделкой
                      {% else %}
                        Без отделки
                      {% endif %}
                    </p>

                    {% if ap.plan_img %}
                    <a class="fancybox" rel="gallery1" href="{{ ap.plan_img.url }}">
                      <img src="{{ ap.plan_img.url }}" class="house-plan-img" alt="plan">
                    </a>
                    {% endif %}
                  </div>
                </div>

                  {% endfor %}
                 </tr>

              </table>
            </div>
          </div>

        {% endfor %}
        </div>
      </div>
    </div>
  </div>
  </div>
{% endblock %}

{% block script %}
<script type="text/javascript">
    var map;

    DG.then(function () {
        map = DG.map('map', {
            center: [{{ complex.lat }}, {{ complex.lon }}],
            zoom: 13
        });

        DG.marker([{{ complex.lat }}, {{ complex.lon }}]).addTo(map).bindPopup('{{ complex.name }}');
    });
</script>
{% endblock %}

agency/service/templates/service/sell-ap.html
{% extends 'base.html' %}

{% block content %}
{% load static %}
<div class="container block">
      <div class="row">
          <div class="col-lg-10 offset-1">
              <h1>Продажа квартир</h1>
              <hr width="40%">
              <p class="sell-ap-info">
                Операции с недвижимостью — это искусство сродни биржевой игре. Оно требует знаний рынка, его конъюнктуры, обладания талантом лицедея и психолога. При отсутствии таковых выгодно продать квартиру вы не сможете. Так что экономить на риелторе — решение не самое лучшее. Это вам подтвердит каждый, кто хоть раз продавал недвижимость. <br>
                <br>
                        Наше агентство предлагает: <br>
                1) Оценку рыночной стоимости квартиры<br>
                2) Качественную рекламу квартиры на ведущих площадках недвижимости<br>
                3) Возможно, у нас уже есть покупатель для вас<br>
                4) Сбор документов по ускоренной схеме
              </p>

              <h1>Оставить заявку на продажу квартиры</h1>
              <hr width="60%">
              <p class="sell-ap-info text-center">
                Оставьте заявку на продажу квартиры. Наш специалист свяжется с вами в ближайшее время.
              </p>

              <form class="sale_order_form" method="post" action="">
                {% csrf_token %}

                <div class="form-group">
                  <input type="text" maxlength="30" class="form-control" id="id_name" name="name" placeholder="Ваше имя" required>
                </div>

                <div class="form-group">
                  <input type="text" class="form-control" maxlength="11" id=id_phone" name="phone" placeholder="Ваш номер" required>
                </div>
                <div class="form-group">
                  <input type="email" class="form-control" maxlength="254" required name="email" id="id_email" placeholder="Ваша почта">
                </div>

                <div class="form-group">
                  <textarea class="form-control message"  required name="message" id="id_message" rows="6" placeholder="Оставьте сообщение...">
                  </textarea>
                </div>

                  <input class="btn btn-primary" type="submit" value="Добавить">
              </form>
          </div>
      </div>
  </div>

{% endblock %}

agency/service/templates/service/service.html
{% extends 'base.html' %}

{% block content %}
{% load static %}

    <div class="container block">
      <div class="row">
          <div class="col-lg-10 offset-1 animate__animated animate__fadeIn">
              <h1>Наши услуги</h1>
              <hr width="214px">
              <p class="article-content text-center about-service">
                Агентство недвижимости “FlatBerry” оказывает широкий спектр услуг, связанных с покупкой, продажей, арендой и обменом жилья г. Ульновск. Если вас интересуют вопросы, связанные с квартирами в Подмосковье, не раздумывая, обращайтесь в наше агентство!
              </p>

              <div class="option">
                  <div class="to-client animate__animated animate__fadeInLeft">
                    <div class="option-info">
                        <h3 class="option-info-title">Покупателям</h3>

                        <a href="catalog-nb/">
                            <p class="option-info-text">-квартиры в новостройках</p>
                        </a>
                        <a href="catalog-ap/">
                            <p class="option-info-text">-покупка квартир</p>
                        </a>
                    </div>
                  </div>

                  <div class="to-owner animate__animated animate__fadeInRight">
                    <div class="option-info">
                    <h3 class="option-info-title">Владельцам</h3>

                        <a href="sell/">
                            <p class="option-info-text">-продать квартиру</p>
                        </a>
                    </div>
                  </div>
              </div>
          </div>
      </div>
  </div>
{% endblock %}