agency/agency/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("mainApp.urls")),
    path('news/', include("mainApp.urls")),
    path('about/', include("mainApp.urls")),
    path('service/', include("service.urls")),
    path('service/catalog-ap/', include("flats.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

agency/flats/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.catalog_ap, name='catalog_ap'),
    path('catalog-ap/<slug:slug>/', views.FlatDetailView.as_view(), name='flat-detail'),
]

agency/flats/models.py
from django.db import models
from .utils import *
import datetime


class Flat(models.Model):
    street = models.CharField(max_length=250, blank=True, verbose_name='Улица')
    house_number = models.IntegerField(blank=True, null=True, verbose_name='Номер дома')
    flat_number = models.IntegerField(verbose_name='Номер квартиры')
    slug = models.SlugField(blank=True, verbose_name='Слаг')
    level = models.IntegerField(verbose_name='Этаж')
    room = models.IntegerField(verbose_name='Кол-во комнат')
    square = models.FloatField(verbose_name='Площадь')
    price = models.DecimalField(max_digits=10, decimal_places=1, verbose_name='Цена')
    description = models.TextField(blank=True, verbose_name='Описание')
    phone_number = models.CharField(max_length=20, blank=True, verbose_name='Номер телефона')
    prev_img = models.ImageField(upload_to='flats/', blank=True, verbose_name='Превью')

    def __str__(self):
        return '%s' % self.street

    def save(self, *args, **kwargs):
        if not self.slug:
            street = from_cyrillic_to_eng(str(self.street))
            self.slug = street + '_' + str(self.house_number) + '_' + str(self.flat_number)
        super().save(*args, **kwargs)


    class Meta:
        verbose_name = 'Квартира'
        verbose_name_plural = 'Квартиры'


class FlatGallery(models.Model):
    flat = models.ForeignKey(Flat, on_delete=models.CASCADE, blank=True, verbose_name='Квартира')
    gal_img = models.ImageField(upload_to='flats/gallery/', blank=True, verbose_name='Фотография')

    class Meta:
        verbose_name = 'Фотография'
        verbose_name_plural = 'Фотографии'


class BuyOrder(models.Model):
    flat = models.ForeignKey(Flat, on_delete=models.CASCADE, blank=True, verbose_name='Квартира')
    name = models.CharField(max_length=30, verbose_name='Имя')
    phone = models.CharField(max_length=11, verbose_name='Номер телефона')
    date = models.DateTimeField(blank=True, null=True, verbose_name='Дата')

    def save(self, *args, **kwargs):
        if not self.date:
            self.date = datetime.datetime.now()
        super().save(*args, **kwargs)

    class Meta:
        verbose_name = 'Заявка на покупку квартиры'
        verbose_name_plural = 'Заявки на покупку квартир'

agency/flats/forms.py
from django import forms
from .models import *


class BuyOrderForm(forms.ModelForm):

    class Meta:
        model = BuyOrder
        fields = ['name', 'phone']
        exclude = [""]

agency/flats/views.py
from django.shortcuts import render
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import DetailView, FormView
from django.http import HttpResponseRedirect

from .forms import *


def catalog_ap(request):
    """Каталог квартир"""
    active = ['service']

    flats_list = Flat.objects.all()
    paginator = Paginator(flats_list, 6)

    page = request.GET.get('page')
    try:
        flats = paginator.page(page)
    except PageNotAnInteger:
        flats = paginator.page(1)
    except EmptyPage:
        flats = paginator.page(paginator.num_pages)
    page_range = paginator.page_range
    return render(request, 'flats/catalog-ap.html', {"flats": flats,
                                                     "page_range": page_range,
                                                     "active": active})


class FlatDetailView(FormView, DetailView):
    """Отображение страницы с квартирой"""
    active = ['service']
    model = Flat
    form_class = BuyOrderForm
    template_name = 'flats/ap-page.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['flats'] = Flat.objects.all()
        context['gallery'] = FlatGallery.objects.filter(flat=context['flat'])
        print(context)
        return context

    def post(self, request, slug, *args, **kwargs):
        form = BuyOrderForm(request.POST or None)
        if request.method == 'POST' and form.is_valid():
            new_form = form.save(commit=False)
            new_form.flat = Flat.objects.get(slug=slug)
            new_form.save()
        return HttpResponseRedirect(self.request.path_info)

agency/flats/templates/flats/ap-page.html
{% extends 'base.html' %}

{% block content %}
{% load static %}

<div class="container block">
      <div class="row">
          <div class="col-lg-10 offset-lg-1 flat-info-wrapper">
              <h3 class="flat-title">Продажа квартиры в г. Ульяновск ул. {{flat.street}} д.{{flat.house_number}} кв. {{flat.flat_number}}</h3>
              <hr width="374px">

              <div class="main-info">
                <div class="short-descr">
                    <p>Комнат: {{flat.room}}</p>
                    <p>Этаж: {{flat.level}}</p>
                    <p>Площадь: {{flat.square}} м2</p>
                    <p>Цена: {{flat.price}} р</p>
                    <p>Телефон: {{flat.phone_number}}</p>
                </div>

                <img src="{{ flat.prev_img.url }}" alt="" class="flat-preview">
              </div>

              <div class="flat-description">
                <h3 class="description-title">Дополнительная информация</h3>
                <p class="description-text">{{ flat.description }}</p>
              </div>

              <div class="gallery-section">
                <h2 class="text-left">Фотографии</h2>

                  <div class="gallery-i">
                      {% if gallery %}
                        {% for img in gallery %}
                          <div class="col-lg-3 col-sm-5 thumb">
                            <a data-fancybox="gallery" href="{{ img.gal_img.url }}">
                              <img class="flat-img" src="{{ img.gal_img.url }}" alt="...">
                            </a>
                          </div>
                        {% endfor %}
                      {% endif %}
                  </div>

            </div>

            <div class="reg-for-view">

                <h3 class="title-reg">Записаться на просмотр квартиры</h3>

               <form class="feedback_form reg_view" method="post">
                {% csrf_token %}
                <div class="form-group mr-2">
                    <input type="text" class="form-control" name="name" maxlength="30" required="" id="id_name" placeholder="Ваше имя">
                </div>

                <div class="form-group">
                    <input type="text" class="form-control" name="phone" maxlength="11" required="" id="id_phone" placeholder="Ваш номер">
                </div>
                   <div class="ml-2">
                       <button type="submit" class="btn btn-primary btn-reg-for-view" id="otpravit">Отправить</button>
                   </div>

              </form>


            </div>

          </div>

      </div>
  </div>

{% endblock %}

agency/flats/templates/flats/catalog-ap.html
{% extends 'base.html' %}
{% load static %}

{% block header %}
<link rel="stylesheet" href="{% static 'mainApp/css/table-catalog.css' %}">
{% endblock %}

{% block content %}

<div class="container block">
  <div class="row">
    <div class="col-lg-10 offset-lg-1 col-sm-12">
      <h1>Каталог квартир</h1>
      <hr width="271px">
      <p class="catalog-ap-description">За всеми этапами проведения сделки проследят профессионалы с большим опытом работы. Так же специалисты компании проведут проверку юридической чистоты сделки и подготовят все необходимые документы для её совершения.
      </p>

        <nav class="page-nav articles-nav ">
                    <ul class="pagination">
                        {% if flats.has_previous %}
                            <a class="prev-el" href="?page={{ flats.previous_page_number }}">
                                <i class="fa fa-arrow-left" aria-hidden="true"></i>
                            </a>
                        {% endif %}

                        {% for n in flats.paginator.page_range %}
                            {% if n > flats.number|add:-4 and n < flats.number|add:4 %}
                                 <li class="pagination-item">
                                     <a href='?page={{ n }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}'>
                                         <p class="page-num {% if n == flats.number %}page-action{% endif %}">{{ n }}</p>
                                     </a>
                                 </li>
                            {% endif %}
                        {% endfor %}

                        {% if flats.has_next %}
                            <a class="prev-el" href="?page={{ flats.next_page_number }}">
                                <i class="fa fa-arrow-right" aria-hidden="true"></i>
                            </a>
                        {% endif %}
                    </ul>
                </nav>


            <div class="table-catalog">
                <table>
                    <tr>
                      <th>Фото</th>
                      <th>Адрес</th>
                      <th>Этаж</th>
                      <th>Комнат</th>
                      <th>Площадь <br> м2</th>
                      <th>Цена</th>
                      <th>Телефон</th>
                    </tr>
                    {% for flat in flats %}
                        <tr>
                          <td>
                              <a class="flat-link" href="{% url 'flat-detail' slug=flat.slug %}">
                                  <img class="table-catalog-img" src="{{ flat.prev_img.url }}">
                              </a>
                          </td>
                          <td>
                              <a class="flat-link" href="{% url 'flat-detail' slug=flat.slug %}">
                                  ул. {{flat.street}} д.{{flat.house_number}}
                              </a>
                          </td>
                          <td>{{flat.level}}</td>
                          <td>{{flat.room}}</td>
                          <td>{{flat.square}}</td>
                          <td>{{flat.price}}</td>
                          <td>{{flat.phone_number}}</td>
                        </tr>
                    {% endfor %}
                </table>
            </div>

        <nav class="page-nav articles-nav ">
                    <ul class="pagination">
                        {% if flats.has_previous %}
                            <a class="prev-el" href="?page={{ flats.previous_page_number }}">
                                <i class="fa fa-arrow-left" aria-hidden="true"></i>
                            </a>
                        {% endif %}

                        {% for n in flats.paginator.page_range %}
                            {% if n > flats.number|add:-4 and n < flats.number|add:4 %}
                                 <li class="pagination-item">
                                     <a href='?page={{ n }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}'>
                                         <p class="page-num {% if n == flats.number %}page-action{% endif %}">{{ n }}</p>
                                     </a>
                                 </li>
                            {% endif %}
                        {% endfor %}

                        {% if flats.has_next %}
                            <a class="prev-el" href="?page={{ flats.next_page_number }}">
                                <i class="fa fa-arrow-right" aria-hidden="true"></i>
                            </a>
                        {% endif %}
                    </ul>
                </nav>

    </div>
  </div>
</div>

{% endblock %}