agency/agency/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("mainApp.urls")),
    path('news/', include("mainApp.urls")),
    path('about/', include("mainApp.urls")),
    path('service/', include("service.urls")),
    path('service/catalog-ap/', include("flats.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

agency/flats/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.catalog_ap, name='catalog_ap'),
    path('catalog-ap/<slug:slug>/', views.FlatDetailView.as_view(), name='flat-detail'),
]

agency/mainApp/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index.as_view(), name='index'),
    path('news/', views.news, name='news'),
    path('about/', views.about, name='about'),
    path('news/<slug:slug>/', views.ArticleDetailView.as_view(), name='article-detail'),
    path('contacts/', views.contacts.as_view(), name='contacts'),
    path('reviews/', views.ReviewsDetailView.as_view(), name='reviews'),
]

agency/mainApp/models.py
from django.db import models
import datetime
from .utils import *


class Article(models.Model):
    title = models.CharField(max_length=50, verbose_name='Заголовок')
    slug = models.SlugField(blank=True, verbose_name='Слаг/Slug')
    description = models.TextField(max_length=215, verbose_name='Краткое описание')
    date = models.DateTimeField(blank=True, verbose_name='Дата')
    views = models.PositiveIntegerField(default=0, blank=True, verbose_name='Кол-во просмотров')
    time_to_read = models.IntegerField(blank=True, verbose_name='Время для прочтения')
    text = models.TextField(verbose_name='Текст статьи')
    img = models.ImageField(upload_to='article/', verbose_name='Фотография статьи', null=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = from_cyrillic_to_eng(str(self.title))
        if not self.date:
            self.date = datetime.datetime.now()
        self.time_to_read = reading_time(str(self.text))
        super().save(*args, **kwargs)

    def __str__(self):
        return '%s' % self.title

    class Meta:
        verbose_name = 'Статья'
        verbose_name_plural = 'Новости'


class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE, null=True, verbose_name='Статья')
    name = models.CharField(max_length=50, verbose_name='Имя')
    comment = models.TextField(verbose_name='Текст комментария')
    date = models.DateTimeField(blank=True, verbose_name='Дата')

    def save(self, *args, **kwargs):
        if not self.date:
            self.date = datetime.datetime.now()
        super().save(*args, **kwargs)

    def __str__(self):
        return '%s' % self.name

    def article_title(self):
        article_title = self.article.title

    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'


class Feedback(models.Model):
    name = models.CharField(max_length=30, verbose_name='Имя')
    phone = models.CharField(max_length=11, verbose_name='Номер телефона')
    email = models.EmailField(verbose_name='Почта')
    message = models.TextField(verbose_name='Сообщение пользователя')
    date = models.DateTimeField(blank=True, null=True, verbose_name='Дата')

    def save(self, *args, **kwargs):
        if not self.date:
            self.date = datetime.datetime.now()
        super().save(*args, **kwargs)

    class Meta:
        verbose_name = 'Обращение'
        verbose_name_plural = 'Обращения'


class Review(models.Model):
    name = models.CharField(max_length=30, verbose_name='Имя')
    last_name = models.CharField(max_length=50, verbose_name='Фамилия')
    message = models.TextField(verbose_name='Отзыв пользователя')
    date = models.DateTimeField(blank=True, null=True, verbose_name='Дата')

    def save(self, *args, **kwargs):
        if not self.date:
            self.date = datetime.datetime.now()
        super().save(*args, **kwargs)

    def __str__(self):
        return '%s' % self.name

    class Meta:
        verbose_name = 'Отзыв'
        verbose_name_plural = 'Отзывы'

agency/mainApp/forms.py
from django import forms
from .models import *


class FormComment(forms.ModelForm):

    class Meta:
        model = Comment
        exclude = [""]
        fields = {"name", "comment"}
        widgets = {
            "comment": forms.Textarea(attrs={
                'placeholder': 'Ваш комментарий',
                'required': '',
                'rows': '8'})
        }


class FeedbackForm(forms.ModelForm):

    class Meta:
        model = Feedback
        fields = ['name', 'phone', 'email', 'message']
        exclude = [""]
        widgets = {
            "comment": forms.Textarea(attrs={
                'placeholder': 'Оставьте сообщение...',
                'required': '',
                'rows': '8'})
        }


class ReviewForm(forms.ModelForm):

    class Meta:
        model = Review
        fields = ['name', 'last_name', 'message']
        exclude = [""]
        widgets = {
            "comment": forms.Textarea(attrs={
                'placeholder': 'Оставьте ваш отзыв',
                'required': '',
                'rows': '8'})
        }

agency/mainApp/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.views.generic.detail import DetailView
from django.views.generic.edit import FormView
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import F

from .forms import *


class index(FormView):
    """Главная страница"""
    active = ['home']
    model = Feedback
    form_class = FeedbackForm
    template_name = 'mainApp/homePage.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['feedback_form'] = FeedbackForm()
        return context

    def post(self, request, *args, **kwargs):
        form = FeedbackForm(request.POST or None)
        if request.method == 'POST' and form.is_valid():
            new_form = form.save(commit=False)
            new_form.save()
        return HttpResponseRedirect(self.request.path_info)


def news(request):
    """Раздел с новостями"""
    active = ['articles']

    article_list = Article.objects.all()
    paginator = Paginator(article_list, 2)

    page = request.GET.get('page')
    try:
        articles = paginator.page(page)
    except PageNotAnInteger:
        articles = paginator.page(1)
    except EmptyPage:
        articles = paginator.page(paginator.num_pages)
    page_range = paginator.page_range
    return render(request, 'mainApp/news.html', {"articles": articles,
                                                 "page_range": page_range,
                                                 "active": active})


def about(request):
    """Раздел 'О нас' """
    active = ['about']
    return render(request, 'mainApp/about.html', locals())


class contacts(FormView):
    """Раздел 'Контакты' """
    active = ['contacts']
    model = Feedback
    form_class = FeedbackForm
    template_name = 'mainApp/contacts.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['feedback_form'] = FeedbackForm()
        return context

    def post(self, request, *args, **kwargs):
        form = FeedbackForm(request.POST or None)
        if request.method == 'POST' and form.is_valid():
            new_form = form.save(commit=False)
            new_form.save()
        return HttpResponseRedirect(self.request.path_info)


class ArticleDetailView(FormView, DetailView):
    """Отдельная статья"""
    active = ['articles']
    model = Article
    form_class = FormComment
    template_name = 'mainApp/article.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['comment_list'] = Comment.objects.filter(article=context['article'])
        context['comment_form'] = FormComment()
        Article.objects.filter(title=context['article']).update(views=F("views") + 1)
        return context

    def post(self, request, slug, *args, **kwargs):
        form = FormComment(request.POST or None)
        if request.method == 'POST' and form.is_valid():
            new_form = form.save(commit=False)
            new_form.article = Article.objects.get(slug=slug)
            new_form.save()
        return HttpResponseRedirect(self.request.path_info)


class ReviewsDetailView(FormView):
    """Отзывы"""
    active = ['reviews']
    model = Review
    form_class = ReviewForm
    template_name = 'mainApp/reviews.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['reviews_list'] = Review.objects.all()
        context['review_form'] = ReviewForm()
        return context

    def post(self, request, *args, **kwargs):
        form = ReviewForm(request.POST or None)
        if request.method == 'POST' and form.is_valid():
            new_form = form.save(commit=False)
            new_form.save()
        return HttpResponseRedirect(self.request.path_info)

agency/mainApp/templates/mainApp/article.html
{% extends "base.html" %}

{% block content %}
{% load static  %}

<div class="container block ">
        <div class="row">
            <div class="col-lg-10 ml-auto mr-auto">
                <div class="article">
                    <img src="{{ article.img.url }}" class="article_img animate__animated animate__fadeInDown" alt="article_img">
                    <div class="article-st">

                        <p class="date article_s animate__animated animate__fadeInLeft">
                          <i class="fa fa-calendar" aria-hidden="true"></i> {{ article.date|date:"d-m-Y" }}
                        </p>
                            <div class="time-date-state animate__animated animate__fadeInRight">
                                <p class="time-read">
                                    <i class="fa fa-clock-o" aria-hidden="true"></i> {{ article.time_to_read }} мин
                                </p>
                                <p class="views article_s">
                                    <i class="fa fa-eye" aria-hidden="true"></i> {{ article.views }}
                                </p>
                            </div>

                      </div>

                      <h1 class="article-t animate__animated animate__fadeIn">{{ article.title }}</h1>
                      <p class="article-content">
                        {{ article.text|linebreaks  }}
                      </p>
                    <h4 class="h-comment">Комментарии: {{ comment_list.count }}</h4>
                    {%  for comment in comment_list %}
                    <div class="comment-block blue">
                        <p class="commentator-name">{{ comment.name }}</p>
                        <p class="comment-text">{{ comment.comment }}</p>
                        <p class="date comment-d"><i class="fa fa-calendar" aria-hidden="true"></i>
                            {{ comment.date|date:"d-m-Y G:i" }}</p>
                    </div>
                    {% endfor %}
                    <h4 class="h-comment">Оставить комментарий</h4>
                    <form class="feedback_form" method="post" action="">
                    {% csrf_token %}
                      <div class="form-group">
                        <input name="name" type="text" class="form-control" required id="id_name" placeholder="Ваше имя">
                      </div>

                      <div class="form-group">
                        <textarea name="comment" class="form-control message" rows="6" placeholder="Ваш комментарий" required id="id_comment" ></textarea>
                      </div>
                     <input class="btn btn-primary" type="submit" value="Добавить">
                    </form>


                </div>

            </div>
        </div>
    </div>

{% endblock %}

agency/mainApp/templates/mainApp/contacts.html
{% extends 'base.html' %}

{% block content %}
{% load static %}
<div class="container block animate__animated animate__swing">
      <div class="row">
          <div class="col-lg-10 offset-lg-1">
              <h1>Наши контакты</h1>
              <hr width="242px">
              <div class="contact-info-wrapper">
                  <div class="contact-fields">
                    <p class="contact-field">Email:</p>
                    <p class="contact-field">Телефон:</p>
                  </div>

                  <div class="contact-info">
                      <p class="contact-info">flatberry@bb.com</p>
                      <p class="contact-info">+7 (900) 800-35-35</p>
                  </div>

              </div>

              <div class="contact-social">
                <a href="#">
                    <img class="social-item contact-item" src="{% static 'mainApp/img/social/instagram.png' %}" alt="">
                  </a>
                  <a href="#">
                    <img class="social-item contact-item" src="{% static 'mainApp/img/social/vk.png' %}" alt="">
                  </a>
                  <a href="#">
                    <img class="social-item contact-item" src="{% static 'mainApp/img/social/telegram.png' %}" alt="">
                  </a>
              </div>

          </div>
      </div>
  </div>

  <div class="blue">
      <div class="container block white">
          <div class="row">
              <div class="col-lg-10 offset-lg-1 animate__animated animate__pulse">
                  <h1>Наши офисы</h1>
                  <hr width="208px" class="white_line">
                  <p class="map-info">Адрес: г. Ульяновск, Московское ш., д. 91</p>
                  <div class="contact-map">
                    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1036.9772016118288!2d48.350706403050566!3d54.30509927573528!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x0!2zNTTCsDE4JzE5LjIiTiA0OMKwMjEnMDUuOSJF!5e0!3m2!1sru!2sru!4v1606814887550!5m2!1sru!2sru" width="770" height="330" frameborder="0" style="border:0;" allowfullscreen="" aria-hidden="false" tabindex="0"></iframe>
                  </div>
              </div>
          </div>
      </div>
  </div>


  <div class="container block">
      <div class="row">
          <div class="col-lg-10 offset-1">
              <h1>Обратная связь</h1>
              <hr width="293px">

              <p class="info_content feedback_content contact-feedback">Если у вас возникли какие-либо вопросы, оставьте свои реквизиты и опишите вопрос, наши специалисты свяжутся с вами в ближайшее время и помогут вам.</p>
          <div class="col-lg-3">

          </div>
             <form class="feedback_form" method="post" action="">
                {% csrf_token %}

                <div class="form-group">
                  <input type="text" maxlength="30" class="form-control" id="id_name" name="name" placeholder="Ваше имя" required>
                </div>

                <div class="form-group">
                  <input type="text" class="form-control" maxlength="11" id=id_phone" name="phone" placeholder="Ваш номер" required>
                </div>
                <div class="form-group">
                  <input type="email" class="form-control" maxlength="254" required name="email" id="id_email" placeholder="Ваша почта">
                </div>

                <div class="form-group">
                  <textarea class="form-control message"  required name="message" id="id_message" rows="6" placeholder="Оставьте сообщение...">
                  </textarea>
                </div>

                  <input class="btn btn-primary" type="submit" value="Добавить">
              </form>
          </div>
      </div>
  </div>

{% endblock %}

agency/mainApp/templates/mainApp/homePage.html
{% extends "base.html" %}

{% block content %}
{% load static  %}
<div class="container">
        <div class="row">
            <div class="slider col-lg-12 animate__animated animate__zoomIn">
                <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
                    <ol class="carousel-indicators">
                      <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                      <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                      <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                    </ol>
                    <div class="carousel-inner">
                      <div class="carousel-item active">
                        <img src="{% static 'mainApp/img/slider/1.jpg' %}" class="d-block w-100" alt="...">
                      </div>
                      <div class="carousel-item">
                        <img src="{% static 'mainApp/img/slider/2.jpg' %}" class="d-block w-100" alt="...">
                      </div>
                      <div class="carousel-item">
                        <img src="{% static 'mainApp/img/slider/3.jpg' %}" class="d-block w-100" alt="...">
                      </div>
                    </div>
                    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                      <span class="sr-only">Previous</span>
                    </a>
                    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                      <span class="carousel-control-next-icon" aria-hidden="true"></span>
                      <span class="sr-only">Next</span>
                    </a>
                  </div>
            </div>
        </div>
    </div>

    <div class="container block ">
      <div class="row">
        <div class=" col-lg-10 offset-lg-1">
          <h1>Агенство недвижимости "FlatBerry"</h1>
          <hr width="60%">
          <p class="info_content">НАШЕ АГЕНТСТВО ПОМОГАЕТ СВОИМ КЛИЕНТАМ СОВЕРШАТЬ ВЫГОДНЫЕ И БЕЗОПАСНЫЕ СДЕЛКИ С НЕДВИЖИМОСТЬЮ</p>
          <div class="info_img">
              <div class="img_item link-hover-solid">
                  <a href="service/catalog-nb/" class="from-home">
                      <img class="img from-home-img" src="{% static 'mainApp/img/flats/новостройки.jpg' %}" alt="">
                      <p class="img_description">Квартиры в новостройках</p>
                  </a>
              </div>

              <div class="img_item link-hover-solid">
                  <a href="service/catalog-ap/" class="from-home">
                      <img class="img from-home-img" src="{% static 'mainApp/img/flats/покупка.jpg' %}" alt="">
                      <p class="img_description">Покупка квартир</p>
                  </a>
              </div>

              <div class="img_item link-hover-solid">
                  <a href="service/sell/" class="from-home">
                      <img class="img from-home-img" src="{% static 'mainApp/img/flats/продажа.jpg' %}" alt="">
                      <p class="img_description">Продажа квартир</p>
                  </a>
              </div>

          </div>
        </div>
      </div>
    </div>

    <div class="info blue">
      <div class="container advantages block">
        <div class="row">
            <div class="col-lg-10 offset-lg-1">
              <h1>Наши преимущества</h1>
              <hr width="40%" class="white_line">
              <div class="adv_items">
                <div class="col-lg-4">
                  <h4>Профессионализм</h4>
                  <p class="advantages_descr">Все наши агенты дипломированные специалисты ведущих ВУЗов страны.</p>
                </div>

                <div class="col-lg-4">
                  <h4>Гарантия</h4>
                  <p class="advantages_descr">Гарантия на услуги нашего агентства до 5 лет с момента совершения сделки.</p>
                </div>
              </div>

              <div class="adv_items">
                <div class="col-lg-4">
                  <h4>Доступность</h4>
                  <p class="advantages_descr">Все наши услуги доступны всем и оплата услуг осуществляется по факту их оказания.</p>
                </div>

                <div class="col-lg-4">
                  <h4>Репутация</h4>
                  <p class="advantages_descr">Каждый сотрудник нашего агентства – дорожит нашей репутацией.</p>
                </div>
              </div>
            </div>
        </div>
      </div>
    </div>


  <div class="container block">
		<div class="row">
			<div class="col-lg-12">

          <h1>Обратная связь</h1>
          <hr width="294px">
          <p class="info_content feedback_content">Если у вас возникли какие-либо вопросы, оставьте свои реквизиты и опишите вопрос, наши специалисты свяжутся с вами в ближайшее время и помогут вам.</p>
          <div class="col-lg-3">

          </div>
          <form class="feedback_form" method="post" action="">
            {% csrf_token %}

            <div class="form-group">
              <input type="text" maxlength="30" class="form-control" id="id_name" name="name" placeholder="Ваше имя" required>
            </div>

            <div class="form-group">
              <input type="text" class="form-control" maxlength="11" id=id_phone" name="phone" placeholder="Ваш номер" required>
            </div>
            <div class="form-group">
              <input type="email" class="form-control" maxlength="254" required name="email" id="id_email" placeholder="Ваша почта">
            </div>

            <div class="form-group">
              <textarea class="form-control message"  required name="message" id="id_message" rows="6" placeholder="Оставьте сообщение...">
              </textarea>
            </div>

              <input class="btn btn-primary" type="submit" value="Добавить">
          </form>


			</div>
		</div>
	</div>

{% endblock %}

agency/mainApp/templates/mainApp/news.html
{% extends 'base.html' %}

{% block content %}
{% load static %}
<div class="container">
        <div class="row">
            <div class="col-lg-10 offset-1">
                <nav class="page-nav articles-nav">
                    <ul class="pagination">
                        {% if articles.has_previous %}
                            <a class="prev-el" href="?page={{ articles.previous_page_number }}">
                                <i class="fa fa-arrow-left" aria-hidden="true"></i>
                            </a>
                        {% endif %}

                        {% for n in articles.paginator.page_range %}
                            {% if n > articles.number|add:-4 and n < articles.number|add:4 %}
                                 <li class="pagination-item">
                                     <a href='?page={{ n }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}'>
                                         <p class="page-num {% if n == articles.number %}page-action{% endif %}">{{ n }}</p>
                                     </a>
                                 </li>
                            {% endif %}
                        {% endfor %}

                        {% if articles.has_next %}
                            <a class="prev-el" href="?page={{ articles.next_page_number }}">
                                <i class="fa fa-arrow-right" aria-hidden="true"></i>
                            </a>
                        {% endif %}
                    </ul>
                </nav>

                <div class="articles animate__animated animate__fadeInLeft">
                  {% for article in articles %}
                  <div class="article-wrapper blue">
                    <img class="article__img" src="{{ article.img.url }}" alt="">

                      <div class="article_description">
                        <h6 class="article-title">{{ article.title }}</h6>
                          <p class="article-text">{{ article.description }}</p>

                          <div class="article-footer">
                            <button class="read-btn">
                              <a class="read-a" href="{% url 'article-detail' slug=article.slug %}">Читать</a>
                            </button>

                            <div class="article-footer-stat">
                              <p class="date">
                                <img class="icons" src="{% static 'mainApp/img/icons/calendar.png' %}" alt="date">
                                 {{ article.date|date:"Y-m-d" }}</p>
                              <p class="views">
                                <img class="icons" src="{% static 'mainApp/img/icons/eye.png' %}" alt=""> {{ article.views }} </p>
                            </div>

                          </div>

                        </div>
                  </div>
                  {% endfor %}
                </div>

                <nav class="page-nav articles-nav">
                    <ul class="pagination">
                        {% if articles.has_previous %}
                            <a class="prev-el" href="?page={{ articles.previous_page_number }}">
                                <i class="fa fa-arrow-left" aria-hidden="true"></i>
                            </a>
                        {% endif %}

                        {% for n in articles.paginator.page_range %}
                            {% if n > articles.number|add:-4 and n < articles.number|add:4 %}
                                 <li class="pagination-item">
                                     <a href='?page={{ n }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}'>
                                         <p class="page-num {% if n == articles.number %}page-action{% endif %}">{{ n }}</p>
                                     </a>
                                 </li>
                            {% endif %}
                        {% endfor %}

                        {% if articles.has_next %}
                            <a class="prev-el" href="?page={{ articles.next_page_number }}">
                                <i class="fa fa-arrow-right" aria-hidden="true"></i>
                            </a>
                        {% endif %}
                    </ul>
                </nav>

            </div>
        </div>
    </div>
{% endblock %}

agency/mainApp/templates/mainApp/reviews.html
{% extends 'base.html' %}

{% block content %}
{% load static %}

<div class="container block">
    <div class="row">
      <div class="col-lg-10 offset-1">
        <h1>Отзывы</h1>
        <hr width="206">
        <p class="review-text">
          Что такое отзыв о работе агентства недвижимости — это признание того, что агентство реально помогает совершать сделки с недвижимостью. Также отзыв об агентстве недвижимости помогает этому агентству сделать свою работу еще лучше, учесть ошибки, как свои, так и других агентств. Ваши отзывы помогают нам быть лучшим агентством недвижимости Ульяновска. Мы каждый день стремимся к улучшению качества обслуживания своих клиентов и росту профессионализма наших сотрудников.
        </p>

        {% if reviews_list %}
        {% for review in reviews_list %}
        <div class="comment-block review-block blue">
          <p class="commentator-name">{{review.last_name}} {{review.name}}</p>
          <p class="comment-text">
            {{review.message}}
          </p>
          <p class="date comment-d">
            <i class="fa fa-calendar" aria-hidden="true"></i>
            {{review.date|date:"Y-m-d"}}
          </p>
        </div>
        {% endfor %}
        {% endif %}




        <div class="col-lg-8 offset-lg-2">
          <h4>Оставьте свой отзыв</h4>
          <div class="reg-for-sell">
            <form class="sell-form" method="POST">
            {% csrf_token %}

              <div class="name-last_name">
                <div class="form-group name-folder">
                  <input type="text" name="name" class="form-control" id="id_name" placeholder="Ваше имя" required>
                </div>

                <div class="form-group name-folder">
                   <input type="text" name="last_name" class="form-control" id="id_last_name" placeholder="Ваше фамилия" required>
                </div>
              </div>


              <div class="form-group">
                <textarea name="message" id="id_message" class="form-control message" rows="6"
                          placeholder="Ваш отзыв"
                          required></textarea>
              </div>

                <input class="btn btn-primary btn-reg-for-view" type="submit" value="Добавить">
            </form>

          </div>
        </div>




    </div>

      </div>
    </div>
  </div>

{% endblock %}